/**
 * Syncs NEXT_PUBLIC_SANITY_* from repo root .env.local into sanity/.env.local
 * as SANITY_STUDIO_* so the Studio build (Vite) inlines the real project ID.
 * Run before `sanity deploy` so the deployed bundle gets the correct API host.
 */
const fs = require("fs");
const path = require("path");

const rootEnvPath = path.resolve(__dirname, "..", "..", ".env.local");
const studioEnvPath = path.resolve(__dirname, "..", ".env.local");

if (!fs.existsSync(rootEnvPath)) {
  console.error("Missing repo root .env.local. Create it with NEXT_PUBLIC_SANITY_PROJECT_ID and NEXT_PUBLIC_SANITY_DATASET.");
  process.exit(1);
}

const rootEnv = fs.readFileSync(rootEnvPath, "utf8");
const lines = rootEnv.split("\n");
let projectId = "";
let dataset = "production";
for (const line of lines) {
  const m = line.match(/^\s*NEXT_PUBLIC_SANITY_PROJECT_ID\s*=\s*(.+)/);
  if (m) projectId = m[1].trim().replace(/^["']|["']$/g, "");
  const d = line.match(/^\s*NEXT_PUBLIC_SANITY_DATASET\s*=\s*(.+)/);
  if (d) dataset = d[1].trim().replace(/^["']|["']$/g, "");
}

if (!projectId || projectId === "placeholder") {
  console.error("NEXT_PUBLIC_SANITY_PROJECT_ID is missing or placeholder in .env.local.");
  process.exit(1);
}

const studioEnv = [
  "# Generated by scripts/sync-env.js - do not edit; values come from repo root .env.local",
  `SANITY_STUDIO_PROJECT_ID=${projectId}`,
  `SANITY_STUDIO_DATASET=${dataset}`,
].join("\n") + "\n";

fs.writeFileSync(studioEnvPath, studioEnv, "utf8");
console.log("Synced SANITY_STUDIO_* to sanity/.env.local for build.");
console.log("Run: npx sanity deploy");